services:
  - type: web
    name: quiet-journal
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: mongodb+srv://aditya:aditya@cluster0.vtea3wk.mongodb.net/
        sync: false
      - key: mysecrettt
        sync: false
      - key: ./DB
        value: /var/data
    disk:
      name: uploads
      mountPath: /var/data
      sizeGB: 1
